# Fixed type arrays

In [1]:
# Fixed type arrays
import array
L = list(range(10))
arr = array.array("i",L)
print(arr)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


# Numpy arrays from lists

In [3]:
# Numpy arrays -> faster operations than fixed type arrays
import numpy as np
np.array(L)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.array([3.14, 2, 4, 6 ]) # type upcast to float

array([3.14, 2.  , 4.  , 6.  ])

In [14]:
np.array([3.14, 2, 4, 6 ], dtype="float32") # specify dtype

array([3.14, 2.  , 4.  , 6.  ], dtype=float32)

In [20]:
# Multidimensional numpy arrays using list iteration and multi dimensional lists
np.array([range(i,i+3) for i in range(2,4)])

array([[2, 3, 4],
       [3, 4, 5]])

# Creating arrays from scratch

In [22]:
# array of zeros
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
# array of 1s
np.ones((3,5), dtype="float32")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [29]:
# array of same value
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [32]:
# array of linear sequence
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [35]:
# array of n evenly spread numbers between start and end
n = 5
start = 0
end = 1
np.linspace(start,end,n)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [38]:
# normal distribution, mean 0 var 1 3X3
np.random.normal(0,1, (3,3))

array([[ 2.10852529,  0.51262999,  0.27431308],
       [-0.74997462,  0.75094125,  0.28622328],
       [-0.28795406,  0.07381377,  0.16965106]])

In [42]:
# uniform distribution between 0 and 1
np.random.random((3,3))

array([[0.33383822, 0.30362316, 0.22365588],
       [0.52151954, 0.58353915, 0.53897236],
       [0.80544727, 0.26548328, 0.33736877]])

In [45]:
# random integers between 1 and 10
np.random.randint(1,10,(3,3))

array([[2, 2, 8],
       [2, 2, 9],
       [7, 3, 8]])

In [47]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
# Empty array
np.empty(3)

array([1., 1., 1.])

# Array manipulations

## Array attributes

In [18]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [55]:
print(x3.ndim)
print(x3.shape)
print(x3.size)
print(x3.dtype)
print(x3.itemsize)
print(x3.nbytes)

3
(3, 4, 5)
60
int64
8
480


## Array slicing

In [16]:
# x[start:stop:step]
x = np.arange(10)
print(x[:5])
print(x[5:])
print(x[4:7])
print(x[::2]) # alternate numbers
print(x[1::2]) # alternate numbers from 1
print(x[::-1]) # reversed
print(x[-2::-1]) # alternate reversed from second last element

[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[8 7 6 5 4 3 2 1 0]


## multidimensional array slices

In [23]:
# works the same way -> specift both slices comma separated
print(x2)
print(x2[:2,:3]) # 2 r 3 c
print(x2[:,::2]) # all rows, alternate cols
print(x2[::-1,::-1]) # reverse

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 5 2]
 [7 6 8]]
[[3 2]
 [7 8]
 [1 7]]
[[7 7 6 1]
 [8 8 6 7]
 [4 2 5 3]]


## Reshape

In [5]:
grid = np.arange(1,10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# newaxis method
x = np.array([1,2,3])
print(x.reshape(3,1))
print(x[:,np.newaxis]) # equivalent

[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


## Array split and concat

In [15]:
# Concat
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [20]:
# 2d array concat
grid = np.array([[1,2,3],[4,5,6]])
print(np.concatenate([grid,grid])) # along x axis
print(np.concatenate([grid,grid],axis = 1)) # zero indexed

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [23]:
print(np.vstack([grid,grid])) # same as first axis concat
print(np.hstack([grid,grid])) # same as second axis concat

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [29]:
# Split
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x,[3,5]) # also works on np array
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [36]:
grid = np.arange(16).reshape(4,4)
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [38]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Computations on np arrays

In [42]:
# using ufuncs for efficient computations
np.random.seed(0)
def compute_reciprocal(val):
    output = np.empty(len(val))
    for i in range(len(val)):
        output[i] = 1/val[i]
    return output
%timeit compute_reciprocal(np.random.randint(1,100,size=100000))
%timeit 1/(np.random.randint(1,100,size=100000))   #ufunc is much faster

45.6 ms ± 1.27 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
6.55 ms ± 264 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [48]:
print(np.arange(5)/np.arange(1,6)) #ufunc with 2 arrays
x = np.arange(9).reshape(3,3)
print(2 ** x)    #2d arrays
print(x ** 2)

[0.         0.5        0.66666667 0.75       0.8       ]
[[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


## Exploring np Ufuncs

In [6]:
x = np.arange(10)
print("x      =",x)
print("x + 5  =",x+5)
print("x - 5  =",x-5)
print("x * 5  =",x*5)
print("x / 5  =",x/5)
print("x // 5 =",x//5)

x      = [0 1 2 3 4 5 6 7 8 9]
x + 5  = [ 5  6  7  8  9 10 11 12 13 14]
x - 5  = [-5 -4 -3 -2 -1  0  1  2  3  4]
x * 5  = [ 0  5 10 15 20 25 30 35 40 45]
x / 5  = [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
x // 5 = [0 0 0 0 0 1 1 1 1 1]


In [10]:
# Specifying output
x = np.arange(5)
y = np.empty(5)
np.multiply(x,10, out=y)
z = x*10.0 # same except the ufunc out is stored to a temp vairable and is then compied to z
print(y)
print(z)

[ 0. 10. 20. 30. 40.]
[ 0. 10. 20. 30. 40.]


In [13]:
# Aggregates
x = np.arange(1,6)
print(np.add.reduce(x))
print(np.add.accumulate(x))

15
[ 1  3  6 10 15]


In [16]:
# Outer products
x = np.arange(1,6)
print(np.multiply.outer(x,x))

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


## Aggregations